django_vote/django_vote/urls.py
from django.contrib import admin
from django.urls import path, include
# from vote.views import vote_new

app_name = 'vote'
urlpatterns = [
    # path('', vote_new, name='vote_new'),
    path('', include('vote.urls')),
    path('admin/', admin.site.urls),
]

django_vote/vote/urls.py
from django.urls import path, re_path
from .views import indexfunc, areafunc,constituencyfunc, vote_new, vote_detail, candidatefunc, contactfunc, confirmfunc, completefunc, resultfunc, summaryfunc

app_name = 'vote'
urlpatterns = [
    path("", indexfunc, name='index'),
    path("contact/", contactfunc, name = 'contact'),
    path("confirm/", confirmfunc, name = 'confirm'),
    path("complete/", completefunc, name = 'complete'),
    path("result/", resultfunc, name = 'result'),
    path("area/", areafunc, name = 'area'),
    path("summary/<str:person_name>", summaryfunc, name = 'summary'),
    path("constituency/<str:prefecture>", constituencyfunc, name = 'constituency'),
    path("constituency/<str:prefecture>/<int:constituency>", candidatefunc, name = 'candidate'),
    path("new/", vote_new, name='vote_new'),
    path("<int:vote_id>", vote_detail, name="vote_detail"),
]

django_vote/vote/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import DateTimeField
# Create your models here.

class Vote(models.Model):
    words = models.TextField('検索ワード', blank=True)
    created_at = models.DateTimeField('投稿日', auto_now_add=True)
    def __str__(self):
        return self.words

class Comment(models.Model):
    serial_id = models.AutoField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    sentence = models.TextField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    comment_datetime = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comment'

class Image(models.Model):
    image_id = models.IntegerField(blank=True, null=True)
    image_url = models.TextField(blank=True, null=True)
    comment_id = models.IntegerField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'image'


class Member(models.Model):
    member_id = models.IntegerField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    party = models.CharField(max_length=15, blank=True, null=True)
    prefecture = models.CharField(max_length=15, blank=True, null=True)
    constituency = models.IntegerField(blank=True, null=True)
    twitter_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member'
        
class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    prefecture = models.CharField(max_length=100, blank=True, null=True)
    constituency = models.IntegerField(blank=True, null=True)
    query = models.TextField(blank=True, null=True)
    search_datetime = models.DateTimeField(auto_now_add = True)

    class Meta:
        managed = False
        db_table = 'users'

class Inquiry(models.Model):
    post_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    subject = models.CharField(max_length=100, blank=True, null=True)
    details = models.TextField(blank=True, null=True)
    posted_datetime = models.DateTimeField(auto_now_add = True)

    class Meta:
        managed = False
        db_table = 'inquiry'

class Area(models.Model):
    area_id = models.IntegerField(primary_key=True)
    prefecture = models.CharField(max_length=15, blank=True, null=True)
    constituency = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'area'

django_vote/vote/forms.py
from django import forms
from vote.models import Vote

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ['words']

django_vote/vote/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from vote.models import Vote
from vote.forms import VoteForm
from ml.get_words_similarity import get_words_similarity
from .models import Member ,Area, Users, Inquiry, Comment
from django_pandas.io import read_frame
from django.db import connection
import pandas as pd

# import pandas as pd
# import numpy as np


def indexfunc(request):
    return render(request, 'index.html')

def contactfunc(request):
    return render(request, 'contact_form.html')   

def confirmfunc(request):
    username = request.POST.get('username')
    email = request.POST.get('email')
    subject = request.POST.get('subject')
    details = request.POST.get('details')
    Inquiry.objects.create(username = username,
                           email = email,
                           subject = subject, 
                           details = details)
    return render(request, 'contact_confirm.html', {'username':username, 
                                                    'email':email, 
                                                    'subject':subject, 
                                                    'details':details})  

def completefunc(request):
    return render(request, 'contact_complete.html')
        
def summaryfunc(request,person_name):
    url = 'vote/wordcloud/' + person_name + '_wordCloud.png'
    return render(request,'wordcloud.html',{'name':person_name, 'url':url})

def resultfunc(request):
    topic = request.POST.get('topic')
    prefecture = request.POST.get('prefecture')
    constituency = request.POST.get('electoral_district')
    #Userテーブルへの行動ログ保存
    Users.objects.create(prefecture = prefecture,
                                   constituency = constituency,
                                   query = topic)
    try:
        # Commentテーブルにおける対象選挙区の候補者の抽出
        candidates = Member.objects.filter(prefecture = prefecture, constituency = constituency)
        candidate_list = Member.objects.filter(prefecture = prefecture, constituency = constituency).values_list('name', flat = True)
        comments = Comment.objects.filter(name__in = [candidate_list])
        comment_df = read_frame(comments, fieldnames=['name', 'sentence', 'comment', 'comment_datetime'])
        member_df = read_frame(candidates, fieldnames=['name', 'party'])

        # キーワードと候補者発言の類似度計算
        candidate_rank, sentence_rank = get_words_similarity(topic, comment_df)
        candidate_rank = pd.merge(candidate_rank, member_df)
        sentence_rank = pd.merge(sentence_rank, member_df)
        candidate_rank = pd.concat([candidate_rank,member_df])[['name', 'party', 'sentence']].drop_duplicates(subset = 'name').fillna('関連発言なし').reset_index()
        return render(request,'search_result.html',{'prefecture':prefecture, 
                                                    'constituency':constituency,
                                                    'topic':topic,
                                                    'candidate_rank':candidate_rank,
                                                    'sentence_rank':sentence_rank, 
                                                    'candidates':candidates
                                                   })
    except ValueError:
        return render(request, 'error.html')

def areafunc(request):
    object_list = Member.objects.all()
    return render(request, 'prefecture_page.html',{'object_list':object_list})

def constituencyfunc(request, prefecture):
    constituency_list = Area.objects.filter(prefecture__contains = prefecture)
    return render(request, 'electoral_district.html',{'constituency_list':constituency_list})

def candidatefunc(request, prefecture, constituency):
    candidate_list = Member.objects.filter(prefecture = prefecture, constituency = constituency)
    return render(request, 'candidate_list.html',{'candidate_list':candidate_list, 'prefecture':prefecture, 'constituency':constituency})



def vote_new(request):
    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.save()
            return redirect(vote_detail, vote_id=vote.pk)
    else:
        form = VoteForm()
    return render(request, "vote/vote_new.html", {'form': form})


def vote_detail(request, vote_id):
    vote = get_object_or_404(Vote, pk=vote_id)
    words = vote.words
    df = get_words_similarity(words)
    context = {'vote': vote, 'df': df}
    
    return render(request, 'vote/vote_detail.html',
                    context)

django_vote/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<html>
<head>
    <meta charset='utf-8'>
    <title>Vote</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'vote/css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
    <div class="container justify-content-between">
        <a href="/" class="navbar-brand">Vote</a>
    </div>
</nav>
<main>
    <div class="container">
        {% block main %}{% endblock %}
    </div>
</main>
</body>
</html>

django_vote/vote/templates/vote/candidate_list.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- 各種メタ情報 -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Voteとは選挙会場にいるあなたの手助けをするアプリです。あなたの投票をよりスムーズに、より効率的に行えるようにサポートします">
        <meta name="format-detection" content="telephone=no,address=no,email=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- ページタイトル -->
        <title>候補者一覧</title>
        <!-- ファビコン -->
        <link rel="icon" href="{% static 'vote/image/hand-peace-o.ico' %}">
        <!-- CSSファイル読み込み -->
        <link rel="stylesheet" href="{% static 'vote/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/common.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/candidate_list.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">

    </head>
    <body>
        <!-- ヘッダー -->
        <header>
            <div class="header-content-area">
                <div class="header-logo">
                    <a href="{% url 'vote:index' %}"><img class="fas fa-hand-peace" src="{% static 'vote/image/hand-peace-o.png' %}"><span>Vote</span></a>
                </div>
            </div>
        </header>

        <!-- メインコンテンツ -->
        <main>
            <div class="main-content-area">
                <!-- 進捗バーエリア -->
                <div class="progressbar-area">
                    <!-- 進捗バーのサークルエリア-->
                    <ul class="circle-item-area">
                        <li class="circle-item selected"><div><p>1</p></div></li>
                        <li class="circle-item selected"><div><p>2</p></div></li>
                        <li class="circle-item selected"><div><p>3</p></div></li>
                    </ul>
                    <!-- 進捗バーの水平線エリア-->
                    <div class="hr-area">
                        <hr>
                        <hr>
                    </div>
                </div>
                <!-- 各ステップ説明文エリア -->
                <ul class="step-description">
                    <li class="step1-description selected">都道府県を選択</li>
                    <li class="step2-description selected">選挙区を選択</li>
                    <li class="step3-description selected">キーワードを選択</li>
                </ul>

                <!-- 検索フォームエリア -->
                <div class="search-form-area">
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input class="keyword-search" type="text" name="topic" size="25" placeholder="キーワード検索">
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
                <!-- 人気トピック見出し -->
                <h3 class="popular-topic-headline">おすすめトピック<i class="fas fa-chart-line"></i></h3>

                <!-- 人気トピックエリア -->
                <div class="popular-topics-area">

                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="旅行・観光">旅行・観光<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="子育て">子育て<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="結婚">結婚<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="給与・所得">給与・所得<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="補助金・給付金">補助金・給付金<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="転職・就職">転職・就職<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="アニメ・鬼滅の刃">アニメ・鬼滅の刃<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="テクノロジー・IT">テクノロジー・IT<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="ふるさと納税">ふるさと納税<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="コロナ">コロナ<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="地震・震災">地震・震災<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="金融・銀行">金融・銀行<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="LGBT">LGBT<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="税金">税金<i class="fas fa-arrow-right"></i></button>
                    </form>
                    <form method="POST" action="{% url 'vote:result' %}">{% csrf_token %}
                        <input type="hidden" name="prefecture" value="{{prefecture}}">
                        <input type="hidden" name="electoral_district" value="{{constituency}}">
                        <button class="popular-topic" type="submit" name="topic" value="年金">年金<i class="fas fa-arrow-right"></i></button>
                    </form>
                </div>
                
                <!-- 候補者見出し -->
                <h3 class="candidate-headline">候補者一覧<i class="fas fa-poll"></i></h3>
                <!-- 候補者エリア -->
                <div class="candidate-area">
                    {% for candidate in candidate_list %}
                    <a class="candidate" href="{% url 'vote:summary' person_name=candidate.name %}">
                        <p class="political-party">{{candidate.party}}</p>
                        <h3 class="candidate-name">{{candidate.name}}</h3>
                    </a>
                    
                    {% endfor %}
                </div>


            </div>
        </main>

        <!-- フッター -->
        <footer>
            <div class="footer-content-area">
                <div class="footer-menu">
                    <a href="{% url 'vote:index' %}"><i class="fas fa-hand-peace"></i>vote</a>
                    <a href="{% url 'vote:contact' %}">お問い合わせ</a>
                    <a href="https://twitter.com/voteforxyztms">Twitter</a>
                </div>
                <!-- 変更点 -->
                <div class="annotation">
                    ※本サイト内で使用しているデータは『国立国会図書館 国会議事録検索システム』を通じて収集したデータ、ならびに
                    各候補者のTwitterアカウントの直近3000件のツイートデータを使用しています。
                </div>
                <!-- ここまで -->
            </div>
        </footer>

    <!-- JavaScriptファイル読み込み -->
    <script src="{% static 'vote/js/animation.js' %}"></script>
    </body>
</html>

django_vote/vote/templates/vote/contact_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- 各種メタ情報 -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Voteとは選挙会場にいるあなたの手助けをするアプリです。あなたの投票をよりスムーズに、より効率的に行えるようにサポートします">
        <meta name="format-detection" content="telephone=no,address=no,email=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- ページタイトル -->
        <title>お問い合わせ内容確認</title>
        <!-- ファビコン -->
        <link rel="icon" href="{% static 'vote/image/hand-peace-o.ico' %}">
        <!-- CSSファイル読み込み -->
        <link rel="stylesheet" href="{% static 'vote/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/common.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/contact_form.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    </head>
    <body>
        <!-- ヘッダー -->
        <header>
            <div class="header-content-area">
                <div class="header-logo">
                    <a href="{% url 'vote:index' %}"><img class="fas fa-hand-peace" src="{% static 'vote/image/hand-peace-o.png' %}"><span>Vote</span></a>
                </div>
            </div>
        </header>
    <body>
        <!-- ヘッダー -->
        <header>
            <div class="header-content-area">
                <div class="header-logo">
                    <a href="{% url 'vote:vote_new' %}"><img class="fas fa-hand-peace" src="{% static 'vote/image/hand-peace-o.png' %}"><span>Vote</span></a>
                </div>
            </div>
        </header>

        <!-- メインコンテンツ -->
        <main>
            <div class="main-content-area">
                <div class="contact-headline">
                    <h2>以下の内容で送信してもよろしいでしょうか？</h2>
                </div>
                <div class="contact-form">
                    <form method="POST" action="{% url 'vote:complete' %}">{% csrf_token %}
                        <div class="user-name">
                            <div class="label">
                                お名前
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <span>{{username}}</span>
                                <input type="hidden" name="username" value="{{username}}">
                            </div>
                        </div>
                        <hr>
                        <div class="e-mail">
                            <div class="label">
                                メールアドレス
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <span>{{email}}</span>
                                <input type="hidden" name="email" value="{{email}}">
                            </div>
                        </div>
                        <hr>
                        <div class="subject">
                            <div class="label">
                                件名
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <span>{{subject}}</span>
                                <input type="hidden" name="subject" value="{{subject}}">
                            </div>
                        </div>
                        <hr>
                        <div class="details">
                            <div class="label">
                                内容
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <p>{{details}}</p>
                                <input type="hidden" name="details" value="{{details}}">
                            </div>
                        </div>
                        <div class="submit">
                            <button type="submit">送信する</button>
                        </div>
                    </form>

                </div>
            </div>

        </main>

        <!-- フッター -->
        <footer>
            <div class="footer-content-area">
                <div class="footer-menu">
                    <a href="{% url 'vote:index' %}"><i class="fas fa-hand-peace"></i>vote</a>
                    <a href="{% url 'vote:contact' %}">お問い合わせ</a>
                    <a href="https://twitter.com/voteforxyztms">Twitter</a>
                </div>
                <!-- 変更点 -->
                <div class="annotation">
                    ※本サイト内で使用しているデータは『国立国会図書館 国会議事録検索システム』を通じて収集したデータ、ならびに
                    各候補者のTwitterアカウントの直近3000件のツイートデータを使用しています。
                </div>
                <!-- ここまで -->
            </div>
        </footer>

    <!-- JavaScriptファイル読み込み -->
    <script src="animation.js"></script>
    </body>
</html>

django_vote/vote/templates/vote/contact_form.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- 各種メタ情報 -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Voteとは選挙会場にいるあなたの手助けをするアプリです。あなたの投票をよりスムーズに、より効率的に行えるようにサポートします">
        <meta name="format-detection" content="telephone=no,address=no,email=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- ページタイトル -->
        <title>お問い合わせフォーム</title>
        <!-- ファビコン -->
        <link rel="icon" href="{% static 'vote/image/hand-peace-o.ico' %}">
        <!-- CSSファイル読み込み -->
        <link rel="stylesheet" href="{% static 'vote/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/common.css' %}">
        <link rel="stylesheet" href="{% static 'vote/css/contact_form.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    </head>
    <body>
        <!-- ヘッダー -->
        <header>
            <div class="header-content-area">
                <div class="header-logo">
                    <a href="{% url 'vote:vote_new' %}"><img class="fas fa-hand-peace" src="{% static 'vote/image/hand-peace-o.png' %}"><span>Vote</span></a>
                </div>
            </div>
        </header>

        <!-- メインコンテンツ -->
        <main>
            <div class="main-content-area">
                <div class="contact-headline">
                    <h2>お問い合わせ</h2>
                    <span>(<span style="color:red;">*</span>は必須入力)</span>
                </div>
                <div class="contact-form">
                    <form method="POST" action="{% url 'vote:confirm' %}">{% csrf_token %}
                        <div class="user-name">
                            <div class="label">
                                お名前
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <input type="text" name="username" placeholder="お名前を入力" maxlength="255" required>
                            </div>
                        </div>
                        <hr>
                        <div class="e-mail">
                            <div class="label">
                                メールアドレス
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <input type="email" name="email" placeholder="メールアドレスを入力" maxlength="255" required>
                            </div>
                        </div>
                        <hr>
                        <div class="subject">
                            <div class="label">
                                件名
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <input type="text" name="subject" placeholder="件名を入力" maxlength="255" required>
                            </div>
                        </div>
                        <hr>
                        <div class="details">
                            <div class="label">
                                内容
                                <span style="color:red;">*</span>
                            </div>
                            <div class="contents">
                                <textarea name="details" required></textarea>
                            </div>
                        </div>
                        <div class="submit">
                            <button type="submit">確認する</button>
                        </div>
                    </form>

                </div>
            </div>

        </main>

        <!-- フッター -->
        <footer>
            <div class="footer-content-area">
                <div class="footer-menu">
                    <a href="{% url 'vote:index' %}"><i class="fas fa-hand-peace"></i>vote</a>
                    <a href="{% url 'vote:contact' %}">お問い合わせ</a>
                    <a href="https://twitter.com/voteforxyztms">Twitter</a>
                </div>
                <!-- 変更点 -->
                <div class="annotation">
                    ※本サイト内で使用しているデータは『国立国会図書館 国会議事録検索システム』を通じて収集したデータ、ならびに
                    各候補者のTwitterアカウントの直近3000件のツイートデータを使用しています。
                </div>
                <!-- ここまで -->
            </div>
        </footer>

    <!-- JavaScriptファイル読み込み -->
    <script src="animation.js"></script>
    </body>
</html>

django_vote/vote/templates/vote/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <div class = 'container'>


        {% for candidate in candidate_list %}
        <div class="alert alert-success" role="alert">
           <p>Contributor:{{candidate.name}}</p>
        </div>
      {% endfor %}
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>